image: drecom/centos-ruby:latest

before_script:
  - gem install bundler -v 2.3.4
  - bundle install

variables:
  RAILS_ENV: 'test'

stages:
  - test

.rspec-default: &rspec-default
  stage: test
  script:
    - bundle exec rubocop
    - bundle exec rspec
  services:
    - mysql:5.7

.use-ruby2_6: &use-ruby2_6
  image: drecom/centos-ruby:2.6.7

.use-ruby2_7: &use-ruby2_7
  image: drecom/centos-ruby:2.7.3

.use-ruby3_0: &use-ruby3_0
  image: drecom/centos-ruby:3.0.2

.use-rails6_0: &use-rails6_0
  variables:
    BUNDLE_GEMFILE: "spec/gemfiles/rails6_0.gemfile"

.use-rails6_1: &use-rails6_1
  variables:
    BUNDLE_GEMFILE: "spec/gemfiles/rails6_1.gemfile"

.use-rails7_0: &use-rails7_0
  variables:
    BUNDLE_GEMFILE: "spec/gemfiles/rails7_0.gemfile"

ruby2.6-rails6.0:
    <<: *rspec-default
    <<: *use-ruby2_6
    <<: *use-rails6_0

ruby2.6-rails6.1:
    <<: *rspec-default
    <<: *use-ruby2_6
    <<: *use-rails6_1

ruby2.7-rails6.0:
    <<: *rspec-default
    <<: *use-ruby2_7
    <<: *use-rails6_0

ruby2.7-rails6.1:
    <<: *rspec-default
    <<: *use-ruby2_7
    <<: *use-rails6_1

ruby2.7-rails7.0:
    <<: *rspec-default
    <<: *use-ruby2_7
    <<: *use-rails7_0

ruby3.0-rails6.0:
    <<: *rspec-default
    <<: *use-ruby3_0
    <<: *use-rails6_0

ruby3.0-rails6.1:
    <<: *rspec-default
    <<: *use-ruby3_0
    <<: *use-rails6_1

ruby3.0-rails7.0:
    <<: *rspec-default
    <<: *use-ruby3_0
    <<: *use-rails7_0

